Chromium compatibility
Insprill/nexusmods-no-premium pull request #3
Opened 2024-05-18 11:16 UTC by MagicJinn

Makes your addon compatible with Chromium.
Big fan of Firefox myself, but it only requires minimal changes to also make it compatible with Chrome. You can either:
Create 2 zip files manually, and include manifest.json in the Firefox one, then rename manifest v3.json to manifest.json and put that in the Chromium zip file.
or run the build.bat file I've included. Keep in mind it only works with 7zip installed. I tried to get it to work with Windows' built in Compress-Archive feature, but that is completely busted for some reason.

Another note, you need a Chrome developer account to upload Chrome extensions, which costs 5$ for some reason. If you don't want to pay that, or if you don't want to merge this pull request at all, I can upload a Chrome version on my account, since I've already had to pay the premium.

2024-05-18 21:11 UTC, Insprill requested changes
Thank you for the PR! I don't mind paying the developer fee to get it published on the Chrome store - I also only use Firefox, so I didn't even think about publishing it there.

2024-05-18 21:11 UTC, Insprill commented on build.bat
I use Linux, so I can't easily run this script. Could you convert it to PowerShell? That's the easiest way to make it cross-platform.

2024-05-18 21:11 UTC, Insprill commented on manifest v3.json
Could the build script also fill in some of the variables like name, version, and description to avoid duplicating it in both files?

2024-05-19 01:29 UTC, MagicJinn commented on manifest v3.json
Latest commit should add the proposed changes. I can't easily test it myself because I'm on windows, so if you could take a quick look to see if it works that would be great!

The reason I originally didn't use Compress-Archive is because it seems to have extremely weird issues with images in particular, which is what the addon I wrote the script for mainly contained. It should be fine for this extension though.

2024-05-19 02:49 UTC, Insprill commented on manifest v3.json
Looks good at a glance! Unfortunately, I'm away until Monday, so I'll get a chance to do a proper review then.

PowerShell is cross-platform. You can easily install it on Windows with `winget`
```
winget install Microsoft.PowerShell
```
You can then run the script with `pwsh ./build.ps1`

2024-05-19 09:10 UTC, MagicJinn commented on manifest v3.json
Oh, I misspoke. I can run it on windows, but what I meant to say is that I can't test whether it works on Linux as well.

2024-06-08 14:18 UTC, MagicJinn commented
Hey there, sorry to bother, any updates on reviewing/merging this PR? Thanks!

2024-06-08 18:08 UTC, Insprill commented
So sorry about the wait! After looking at this again, is there any reason why we can't use the same Manifest v3 file on Firefox and Chromium and use the same zip for both? Correct me if I'm wrong here, but having a v2 and a v3 seems redundant.

2024-06-08 18:14 UTC, MagicJinn commented
I have seen certain extensions use the same manifest for both versions, but with these extensions it came with permission issues (Firefox wouldn't automatically prompt you for the permissions, you would have to manually enable them) and other issues. This is an approach that makes sure all users get the same experience across browsers, and is used in other browser extensions.

In this example, you can try to load the Chromium.zip file with Firefox in about:debugging, and notice it did not automatically enable access to nexusmods.com.

2024-06-08 18:21 UTC, Insprill commented
I just tested the Chromium version on Firefox, and it worked fine for me. I don't have any objections to having them separated though if it's not going to be reliable having them shared.

2024-06-08 18:21 UTC, Insprill approved these changes
LGTM, Thank you!

2024-06-08 18:21 UTC, merged

2024-06-08 18:23 UTC, MagicJinn commented
> I just tested the Chromium version on Firefox, and it worked fine for me.

That is strange. When I load it, it doesn't work by default, and shows the little green dot underneath the addon button. Anyway, thanks for the merge!

2024-06-08 20:06 UTC, Insprill commented
Just a quick update here since there wasn't an issue to track this - I've submitted the extension for review, so hopefully it'll be available for Chrome shortly :partying_face:

2024-06-08 20:58 UTC, MagicJinn commented
Cool! Most exited about the #1 fix, but glad Chrome users can also use this great extension!

2024-06-08 21:15 UTC, Insprill commented
I updated the Firefox extension about an hour ago; you may have to manually check for updates to get it now.